In [3]:
import numpy as np


In [4]:
X = np.array([1.5, 2.0, 0.5])
print(X)

[1.5 2.  0.5]


In [5]:
W1 = np.array([0.2, 0.8, -0.5])
b1 = 2.0
Z1 = np.dot(W1, X) + b1
print(Z1)

3.6500000000000004


In [6]:
def relu(Z):
    return np.maximum(0, Z)

A1 = relu(Z1)
print(A1)

3.6500000000000004


In [7]:
X = np.array([1.5, 2.0, 0.5])
W = np.array([
    [0.2, 0.8, -0.5],
    [0.5, -0.1, 0.3]
    ])
b = np.array([2.0, 0.5])
Z = np.dot(W, X) + b
def ReLU(Z):
    return np.maximum(0, Z)
A = ReLU(Z)
print(Z)
print(A)

[3.65 1.2 ]
[3.65 1.2 ]


In [8]:
W2 = np.array([[0.1, -0.2],
            [-0.3, 0.4]])
b2 = np.array([0.1, 0.2])
Z2 = np.dot(W2, A) + b2

def softmax(Z):
    exp_Z = np.exp(Z)
    return exp_Z / np.sum(exp_Z)
A2 = softmax(Z2)
print(A2)
#output sum is equal to 1 so that's what softmax function do, layer 1 65% sure and layer 2 35% sure. 

[0.65475346 0.34524654]


In [9]:
Y = np.array ([0, 1]) 
error = A2 - Y
print(Y)
print(error)

[0 1]
[ 0.65475346 -0.65475346]


In [10]:
dZ2 = A2 - Y
DW2 = np.outer(dZ2, A)
db2 = dZ2
print("Change needed for b2:", db2)
print("Change needed for W2:", DW2)

Change needed for b2: [ 0.65475346 -0.65475346]
Change needed for W2: [[ 2.38985013  0.78570415]
 [-2.38985013 -0.78570415]]


In [11]:
dZ1 = np.dot(W2.T, dZ2) * (Z > 0)
dW1 = np.outer(dZ1, X)
db1 = dZ1 
print(dZ1)
print(dW1)
print(db1)

[ 0.26190138 -0.39285208]
[[ 0.39285208  0.52380277  0.13095069]
 [-0.58927811 -0.78570415 -0.19642604]]
[ 0.26190138 -0.39285208]


In [12]:
learning_rate = 0.1
W = W - learning_rate * dW1
b = b - learning_rate * db1
print("Updated W:", W)

W2 = W2 - learning_rate * DW2
b2 = b2 - learning_rate * db2
print("Updated W2:", W2)

Updated W: [[ 0.16071479  0.74761972 -0.51309507]
 [ 0.55892781 -0.02142958  0.3196426 ]]
Updated W2: [[-0.13898501 -0.27857042]
 [-0.06101499  0.47857042]]


In [15]:
epochs = 50

for i in range(epochs):
    Z = np.dot(W, X) + b
    A = np.maximum(0, Z)
    
    Z2 = np.dot(W2, A) + b2
    A2 = softmax(Z2)
    
    dZ2 = A2 - Y
    DW2 = np.outer(dZ2, A)
    db2 = dZ2
    dZ1 = np.dot(W2.T, dZ2) * (Z > 0)
    dW1 = np.outer(dZ1, X)
    db1 = dZ1
    
    W = W - learning_rate * dW1
    b = b - learning_rate * db1
    W2 = W2 - learning_rate * DW2
    b2 = b2 - learning_rate * db2
    
    if i % 5 == 0:
        print(f"Epoch {i} - Network Prediction: {A2}")
        
print(f"\nFinal Prediction after {epochs} Epochs: {A2}")

Epoch 0 - Network Prediction: [0.00412427 0.99587573]
Epoch 5 - Network Prediction: [0.00372234 0.99627766]
Epoch 10 - Network Prediction: [0.00338856 0.99661144]
Epoch 15 - Network Prediction: [0.00310719 0.99689281]
Epoch 20 - Network Prediction: [0.00286696 0.99713304]
Epoch 25 - Network Prediction: [0.0026596 0.9973404]
Epoch 30 - Network Prediction: [0.00247889 0.99752111]
Epoch 35 - Network Prediction: [0.00232008 0.99767992]
Epoch 40 - Network Prediction: [0.00217948 0.99782052]
Epoch 45 - Network Prediction: [0.00205418 0.99794582]

Final Prediction after 50 Epochs: [0.00196337 0.99803663]


**MNIST DIGIT CLASSIFIER**

In [25]:
X = np.array([
    [1.5, 0.5],
    [2.0, 1.0],
    [0.5, 1.5]  
]) 

Y = np.array([
    [1, 0],
    [0, 1]
])

print(X.shape)
print(Y.shape)

(3, 2)
(2, 2)


In [26]:
b1 = np.array([[2.0], [0.5]])
b2 = np.array([[0.1], [0.2]])

Z1 = np.dot(W, X) + b1
A1 = np.maximum(0, Z1)

Z2 = np.dot(W2, A1) + b2

def softmax_batch(Z):
    exp_Z =np.exp(Z)
    return exp_Z / np.sum(exp_Z, axis=0, keepdims=True)

A2 = softmax_batch(Z2)

print(A1)
print(A2)

[[3.49550383 1.70077288]
 [3.10070111 0.        ]]
[[0.00178633 0.64582125]
 [0.99821367 0.35417875]]


In [27]:
m = X_shape_colums = 2
dZ2 = A2 -Y
dW2 = (1/m) * np.dot(dZ2, A1.T)
db2 = (1/m) * np.sum(dZ2, axis =1, keepdims=True)

print(dW2)
print(db2)

[[-1.19543221 -1.54758112]
 [ 1.19543221  1.54758112]]
[[-0.17619621]
 [ 0.17619621]]


In [28]:
dZ1 = np.dot(W2.T, dZ2) * (Z1>0)
dW1 = (1/m) * np.dot(dZ1, X.T)
db1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)

print(dW1)
print(db1)

[[-0.24192934 -0.2782259   0.09674312]
 [ 1.85093541  2.46791388  0.61697847]]
[[-0.07259311]
 [ 1.23395694]]


In [31]:
epochs = 200
for i in range(epochs + 1):
    Z1 = np.dot(W, X) + b1
    A1 = np.maximum(0, Z1)
    
    Z2 = np.dot(W2, A1) + b2
    A2 = softmax_batch(Z2)
    
    dZ2 = A2 - Y
    dW2 = (1/m) * np.dot(dZ2, A1.T)
    db2 = (1/m) * np.sum(dZ2, axis=1, keepdims=True)
    
    dZ1 = np.dot(W2.T, dZ2) * (Z1 > 0)
    dW1 = (1/m) * np.dot(dZ1, X.T)
    db1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)
    
    W = W - learning_rate * dW1
    b = b - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    
    if i % 20 == 0:
        print(f"Epoch {i}")
        print(f"Image 1(cat) prediction: {A2[:, 0]}")
        print(f"Image 2(dog) prediction: {A2[:, 1]}\n")

Epoch 0
Image 1(cat) prediction: [0.99570939 0.00429061]
Image 2(dog) prediction: [0.04567482 0.95432518]

Epoch 20
Image 1(cat) prediction: [0.99623062 0.00376938]
Image 2(dog) prediction: [0.04236688 0.95763312]

Epoch 40
Image 1(cat) prediction: [0.99651889 0.00348111]
Image 2(dog) prediction: [0.03939649 0.96060351]

Epoch 60
Image 1(cat) prediction: [0.99676342 0.00323658]
Image 2(dog) prediction: [0.03684613 0.96315387]

Epoch 80
Image 1(cat) prediction: [0.99697433 0.00302567]
Image 2(dog) prediction: [0.03459766 0.96540234]

Epoch 100
Image 1(cat) prediction: [0.99725465 0.00274535]
Image 2(dog) prediction: [0.03260179 0.96739821]

Epoch 120
Image 1(cat) prediction: [0.99740837 0.00259163]
Image 2(dog) prediction: [0.03081833 0.96918167]

Epoch 140
Image 1(cat) prediction: [0.99754436 0.00245564]
Image 2(dog) prediction: [0.02921538 0.97078462]

Epoch 160
Image 1(cat) prediction: [0.99773682 0.00226318]
Image 2(dog) prediction: [0.02776782 0.97223218]

Epoch 180
Image 1(cat) pr