In [1]:
import numpy as np


In [2]:
X = np.array([1.5, 2.0, 0.5])
print(X)

[1.5 2.  0.5]


In [3]:
W1 = np.array([0.2, 0.8, -0.5])
b1 = 2.0
Z1 = np.dot(W1, X) + b1
print(Z1)

3.6500000000000004


In [4]:
def relu(Z):
    return np.maximum(0, Z)

A1 = relu(Z1)
print(A1)

3.6500000000000004


In [5]:
X = np.array([1.5, 2.0, 0.5])
W = np.array([
    [0.2, 0.8, -0.5],
    [0.5, -0.1, 0.3]
    ])
b = np.array([2.0, 0.5])
Z = np.dot(W, X) + b
def ReLU(Z):
    return np.maximum(0, Z)
A = ReLU(Z)
print(Z)
print(A)

[3.65 1.2 ]
[3.65 1.2 ]


In [6]:
W2 = np.array([[0.1, -0.2],
            [-0.3, 0.4]])
b2 = np.array([0.1, 0.2])
Z2 = np.dot(W2, A) + b2

def softmax(Z):
    exp_Z = np.exp(Z)
    return exp_Z / np.sum(exp_Z)
A2 = softmax(Z2)
print(A2)
#output sum is equal to 1 so that's what softmax function do, layer 1 65% sure and layer 2 35% sure. 

[0.65475346 0.34524654]


In [7]:
Y = np.array ([0, 1]) 
error = A2 - Y
print(Y)
print(error)

[0 1]
[ 0.65475346 -0.65475346]


In [8]:
dZ2 = A2 - Y
DW2 = np.outer(dZ2, A)
db2 = dZ2
print("Change needed for b2:", db2)
print("Change needed for W2:", DW2)

Change needed for b2: [ 0.65475346 -0.65475346]
Change needed for W2: [[ 2.38985013  0.78570415]
 [-2.38985013 -0.78570415]]


In [9]:
dZ1 = np.dot(W2.T, dZ2) * (Z > 0)
dW1 = np.outer(dZ1, X)
db1 = dZ1 
print(dZ1)
print(dW1)
print(db1)

[ 0.26190138 -0.39285208]
[[ 0.39285208  0.52380277  0.13095069]
 [-0.58927811 -0.78570415 -0.19642604]]
[ 0.26190138 -0.39285208]


In [10]:
learning_rate = 0.1
W = W - learning_rate * dW1
b = b - learning_rate * db1
print("Updated W:", W)

W2 = W2 - learning_rate * DW2
b2 = b2 - learning_rate * db2
print("Updated W2:", W2)

Updated W: [[ 0.16071479  0.74761972 -0.51309507]
 [ 0.55892781 -0.02142958  0.3196426 ]]
Updated W2: [[-0.13898501 -0.27857042]
 [-0.06101499  0.47857042]]


In [11]:
epochs = 50

for i in range(epochs):
    Z = np.dot(W, X) + b
    A = np.maximum(0, Z)
    
    Z2 = np.dot(W2, A) + b2
    A2 = softmax(Z2)
    
    dZ2 = A2 - Y
    DW2 = np.outer(dZ2, A)
    db2 = dZ2
    dZ1 = np.dot(W2.T, dZ2) * (Z > 0)
    dW1 = np.outer(dZ1, X)
    db1 = dZ1
    
    W = W - learning_rate * dW1
    b = b - learning_rate * db1
    W2 = W2 - learning_rate * DW2
    b2 = b2 - learning_rate * db2
    
    if i % 5 == 0:
        print(f"Epoch {i} - Network Prediction: {A2}")
        
print(f"\nFinal Prediction after {epochs} Epochs: {A2}")

Epoch 0 - Network Prediction: [0.16357323 0.83642677]
Epoch 5 - Network Prediction: [0.0381412 0.9618588]
Epoch 10 - Network Prediction: [0.02102171 0.97897829]
Epoch 15 - Network Prediction: [0.01430157 0.98569843]
Epoch 20 - Network Prediction: [0.01074676 0.98925324]
Epoch 25 - Network Prediction: [0.00856063 0.99143937]
Epoch 30 - Network Prediction: [0.00708656 0.99291344]
Epoch 35 - Network Prediction: [0.00602862 0.99397138]
Epoch 40 - Network Prediction: [0.00523425 0.99476575]
Epoch 45 - Network Prediction: [0.00461699 0.99538301]

Final Prediction after 50 Epochs: [0.00421467 0.99578533]


**MNIST DIGIT CLASSIFIER**

In [12]:
X = np.array([
    [1.5, 0.5],
    [2.0, 1.0],
    [0.5, 1.5]  
]) 

Y = np.array([
    [1, 0],
    [0, 1]
])

print(X.shape)
print(Y.shape)

(3, 2)
(2, 2)


In [13]:
b1 = np.array([[2.0], [0.5]])
b2 = np.array([[0.1], [0.2]])

Z1 = np.dot(W, X) + b1
A1 = np.maximum(0, Z1)

Z2 = np.dot(W2, A1) + b2

def softmax_batch(Z):
    exp_Z =np.exp(Z)
    return exp_Z / np.sum(exp_Z, axis=0, keepdims=True)

A2 = softmax_batch(Z2)

print(A1)
print(A2)

[[3.71298647 2.18391579]
 [2.00354133 1.5326761 ]]
[[0.00651429 0.03281177]
 [0.99348571 0.96718823]]


In [14]:
m = X_shape_colums = 2
dZ2 = A2 -Y
dW2 = (1/m) * np.dot(dZ2, A1.T)
db2 = (1/m) * np.sum(dZ2, axis =1, keepdims=True)

print(dW2)
print(db2)

[[-1.80857043 -0.97009993]
 [ 1.80857043  0.97009993]]
[[-0.48033697]
 [ 0.48033697]]


In [15]:
dZ1 = np.dot(W2.T, dZ2) * (Z1>0)
dW1 = (1/m) * np.dot(dZ1, X.T)
db1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)

print(dW1)
print(db1)

[[0.5451561  0.72282919 0.16553626]
 [0.80196415 1.06333415 0.24351584]]
[[0.35534618]
 [0.52274   ]]


In [16]:
epochs = 200
for i in range(epochs + 1):
    Z1 = np.dot(W, X) + b1
    A1 = np.maximum(0, Z1)
    
    Z2 = np.dot(W2, A1) + b2
    A2 = softmax_batch(Z2)
    
    dZ2 = A2 - Y
    dW2 = (1/m) * np.dot(dZ2, A1.T)
    db2 = (1/m) * np.sum(dZ2, axis=1, keepdims=True)
    
    dZ1 = np.dot(W2.T, dZ2) * (Z1 > 0)
    dW1 = (1/m) * np.dot(dZ1, X.T)
    db1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)
    
    W = W - learning_rate * dW1
    b = b - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    
    if i % 20 == 0:
        print(f"Epoch {i}")
        print(f"Image 1(cat) prediction: {A2[:, 0]}")
        print(f"Image 2(dog) prediction: {A2[:, 1]}\n")

Epoch 0
Image 1(cat) prediction: [0.00651429 0.99348571]
Image 2(dog) prediction: [0.03281177 0.96718823]

Epoch 20
Image 1(cat) prediction: [0.75142241 0.24857759]
Image 2(dog) prediction: [0.37463983 0.62536017]

Epoch 40
Image 1(cat) prediction: [0.90024864 0.09975136]
Image 2(dog) prediction: [0.1492658 0.8507342]

Epoch 60
Image 1(cat) prediction: [0.95491421 0.04508579]
Image 2(dog) prediction: [0.066934 0.933066]

Epoch 80
Image 1(cat) prediction: [0.97407731 0.02592269]
Image 2(dog) prediction: [0.03832912 0.96167088]

Epoch 100
Image 1(cat) prediction: [0.9827035 0.0172965]
Image 2(dog) prediction: [0.0255139 0.9744861]

Epoch 120
Image 1(cat) prediction: [0.9873624 0.0126376]
Image 2(dog) prediction: [0.01861226 0.98138774]

Epoch 140
Image 1(cat) prediction: [0.99020175 0.00979825]
Image 2(dog) prediction: [0.01441414 0.98558586]

Epoch 160
Image 1(cat) prediction: [0.99208273 0.00791727]
Image 2(dog) prediction: [0.01163689 0.98836311]

Epoch 180
Image 1(cat) prediction: [0